name: adt-present-service
volumes:
  postgres_data:
networks:
  internal:
    name: internal
  exposed:
    name: exposed
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - internal